services/web/config/routes.rb
Rails.application.routes.draw do
  resources :bonus_grades
  resources :buttons, only: %i[index]
  resources :student_device_mappings
  resources :question_responses
  resources :clicks
  resources :lessons do
    resource :evaluate, only: %i[show], controller: :lesson_evaluations do
      put :update_benchmark, path: :benchmark
    end
  end
  resources :questions do
    member { post :stop }
  end
  resources :students do
    member { post :adjust_score }
  end
  resources :school_classes do
    resource :seating_plan, only: %i[update show]
  end
  resource :current_school_classes, only: %i[update]
  devise_for :users

  root 'lesson_executions#show'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

services/web/app/models/student.rb
class Student < ApplicationRecord
  strip_attributes
  belongs_to :school_class
  has_many :bonus_grades, dependent: :destroy
  has_many :clicks, dependent: :nullify
  has_many :question_responses, dependent: :destroy
  has_many :questions_that_he_responded_to,
           through: :question_responses, class_name: 'Question'
  has_many :student_device_mappings, dependent: :destroy

  scope :newest_first, -> { order(created_at: :desc) }
  scope :that_participated_in,
        lambda { |lesson:|
          threshold =
            Rails.application.config.clickr
              .student_absent_if_lesson_sum_less_than_or_equal_to
          # TODO Performance: group by having SUM() >
          where(school_class: lesson.school_class).select { |s|
            s.question_response_sum_for(lesson: lesson) > threshold
          }
        }

  validates :name, presence: true, uniqueness: { scope: :school_class }
  validates :seat_row,
            presence: true,
            numericality: { only_integer: true },
            uniqueness: { scope: %i[school_class seat_col] }
  validates :seat_col,
            presence: true,
            numericality: { only_integer: true },
            uniqueness: { scope: %i[school_class seat_row] }

  def question_response_sum
    question_responses.sum(:score)
  end

  def question_response_sum_for_most_recent_lesson
    question_response_sum_for lesson: school_class.most_recent_lesson or
      return 0
  end

  def question_response_sum_for(lesson:)
    question_responses.where(lesson: lesson).sum(:score)
  end

  def question_response_percentage_for(lesson:, benchmark: lesson.benchmark)
    return 1.0 if benchmark == 0.0

    percentage = question_response_sum_for(lesson: lesson).to_f / benchmark
    [1.0, percentage].min
  end

  def nth_incomplete_mapping
    student_device_mappings.incomplete.first&.nth_incomplete
  end

  def responded_to_most_recent_question
    most_recent_question = school_class.most_recent_question
    return false if !most_recent_question

    question_responses.where(question: most_recent_question).exists?
  end

  def spam_count
    clicks.spam_count
  end
end

services/web/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[edit update destroy adjust_score]
  before_action :set_student_with_includes, only: %i[show]
  before_action :set_browser_window_id, only: :adjust_score

  # GET /students
  # GET /students.json
  def index
    @students = Student.includes(:school_class).newest_first
  end

  # GET /students/1
  # GET /students/1.json
  def show; end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit; end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        SchoolClassChannel.broadcast_to(
          @student.school_class,
          type: SchoolClassChannel::STUDENT,
          browser_window_id: params[:browser_window_id]
        )
        if params[:create_incomplete_mapping]
          @student_device_mapping =
            StudentDeviceMapping.create!(
              student: @student, school_class_id: @student.school_class_id
            )
        end
        notice =
          [
            t('.notice'),
            (t('.mapping_notice') if @student_device_mapping)
          ].compact.join('<br/>')

        format.html { redirect_to @student, notice: notice }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json do
          render json: @student.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        SchoolClassChannel.broadcast_to(
          @student.school_class,
          type: SchoolClassChannel::STUDENT,
          browser_window_id: params[:browser_window_id]
        )
        format.html { redirect_to @student, notice: t('.notice') }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json do
          render json: @student.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: t('.notice') }
      format.json { head :no_content }
    end
  end

  def adjust_score
    lesson_id = params[:lesson_id]
    lesson =
      if lesson_id
        Lesson.find(lesson_id)
      else
        @student.school_class.most_recent_lesson
      end
    amount = params[:amount]

    question_response =
      @student.question_responses.create(
        score: amount, lesson: lesson, school_class: @student.school_class
      )

    respond_to do |format|
      if question_response.errors.empty?
        SchoolClassChannel.broadcast_to(
          @student.school_class,
          type: SchoolClassChannel::CLICK, browser_window_id: @browser_window_id
        )
        format.js do
          redirect_to edit_student_path(@student), notice: t('.success')
        end
        format.json { head :no_content }
      else
        format.js do
          redirect_to edit_student_path(@student), alert: t('.error')
        end
        format.json do
          render json: question_response.errors, status: :bad_request
        end
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end

  def set_student_with_includes
    @student = Student.includes(:school_class).find(params[:id])
  end

  def set_browser_window_id
    @browser_window_id = params[:browser_window_id]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def student_params
    params.require(:student).permit(
      :school_class_id,
      :name,
      :seat_row,
      :seat_col
    )
  end
end

services/web/app/views/students/_bonus_grades.html.haml
%h1.title
  .icon
    = icon('fas', 'medal')
  = t('bonus_grades.title')
%table.table.is-striped.is-hoverable
  %thead
    %tr
      %th= t('common.date')
      %th= t('bonus_grades.percentage')
      %th
  %tbody
    - @student.bonus_grades.newest_first.each do |bonus_grade|
      %tr
        %td= I18n.l bonus_grade.created_at, format: :short
        %td
          = percentage(bonus_grade.percentage)
        %td
          .buttons
            = link_to t('common.destroy'), bonus_grade, method: :delete, data: { confirm: t('common.are_you_sure') }, class: 'button is-danger'

services/web/app/views/students/_form.html.haml
= form_with model: @student, local: true do |f|
  = render "layouts/error_messages", f: f
  -# = f.collection_select_with_label :school_class_id, SchoolClass.all, :id, :name, {}, autofocus: true
  = f.text_field_with_label :name
  -# = f.text_field_with_label :seat_row
  -# = f.text_field_with_label :seat_col
  .buttons
    = f.submit_primary t('common.save')
    = yield

services/web/app/views/students/_lessons.html.haml
%h1.title
  .icon
    = icon('fas', 'paper-plane')
  = t('lessons.title')
%table.table.is-striped.is-hoverable
  %thead
    %tr
      %th= t('lessons.title')
      %th= t('common.date')
      %th= t('.response_sum')
      %th= t('.number_of_questions')
      %th= t('.question_score_sum')
      %th= t('lessons.benchmark')
      %th
  %tbody
    - @student.school_class&.lessons.newest_first.with_participation_of(student: @student).each do |lesson|
      %tr
        %td= link_to lesson.name, lesson_evaluate_path(lesson)
        %td= I18n.l lesson.created_at, format: :short
        %td
          = "#{@student.question_response_sum_for lesson: lesson} (#{percentage(@student.question_response_percentage_for(lesson: lesson))})"
        %td= lesson.questions.count
        %td= lesson.question_score_sum
        %td= lesson.benchmark
        %td
          .buttons
            = link_to '-', adjust_score_student_path(@student, lesson_id: lesson.id, amount: -1), method: :post, class: 'button', title: t('common.decrement'), remote: true, data: { 'turbolinks-scroll': true }
            = link_to '+', adjust_score_student_path(@student, lesson_id: lesson.id, amount: 1), method: :post, class: 'button', title: t('common.increment'), remote: true, data: { 'turbolinks-scroll': true }

services/web/app/views/students/edit.html.haml
%h1.title= t('.title')
= render 'form' do
  = link_to t('common.back'), students_path, class: 'button is-danger'
%hr/
.columns
  .column.is-8
    = render 'lessons'
  .column.is-4
    = render 'bonus_grades'

services/web/app/views/students/index.html.haml
%h1.title= t('.title')
= link_to t('common.new'), new_student_path, class: 'button is-primary'
%table.table.is-striped.is-hoverable
  %thead
    %tr
      %th= t('school_classes.title')
      %th= t('common.name')
      %th= t('students.seat_row')
      %th= t('students.seat_col')
      %th
  %tbody
    - @students.each do |student|
      %tr
        %td= student.school_class&.name
        %td= student.name
        %td= student.seat_row
        %td= student.seat_col
        %td
          .buttons
            = link_to t('common.show'), student_path(student), class: 'button'
            = link_to t('common.edit'), edit_student_path(student), class: 'button'
            = link_to t('common.destroy'), student, method: :delete, data: { confirm: t('common.are_you_sure') }, class: 'button is-danger'

services/web/app/views/students/new.html.haml
%h1.title= t('.title')
= render 'form' do
  = link_to t('common.back'), students_path, class: 'button is-danger'

services/web/app/views/students/show.html.haml
%p
  %b= "#{t('school_classes.title')}:"
  = @student.school_class&.name
%p
  %b= "#{t('common.name')}:"
  = @student.name
%p
  %b= "#{t('students.seat_row')}:"
  = @student.seat_row
%p
  %b= "#{t('students.seat_col')}:"
  = @student.seat_col
.buttons
  = link_to t('common.edit'), edit_student_path(@student), class: 'button is-primary'
  = link_to t('common.back'), students_path, class: 'button'
%hr/
.columns
  .column.is-8
    = render 'lessons'
  .column.is-4
    = render 'bonus_grades'