services/web/config/routes.rb
Rails.application.routes.draw do
  resources :bonus_grades
  resources :buttons, only: %i[index]
  resources :student_device_mappings
  resources :question_responses
  resources :clicks
  resources :lessons do
    resource :evaluate, only: %i[show], controller: :lesson_evaluations do
      put :update_benchmark, path: :benchmark
    end
  end
  resources :questions do
    member { post :stop }
  end
  resources :students do
    member { post :adjust_score }
  end
  resources :school_classes do
    resource :seating_plan, only: %i[update show]
  end
  resource :current_school_classes, only: %i[update]
  devise_for :users

  root 'lesson_executions#show'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

services/web/app/controllers/school_classes_controller.rb
class SchoolClassesController < ApplicationController
  before_action :set_school_class, only: %i[show edit update destroy]

  # GET /school_classes
  # GET /school_classes.json
  def index
    @school_classes = SchoolClass.newest_first
  end

  # GET /school_classes/1
  # GET /school_classes/1.json
  def show; end

  # GET /school_classes/new
  def new
    session[:redirect_to] = request.env['HTTP_REFERER']
    @school_class = SchoolClass.new
  end

  # GET /school_classes/1/edit
  def edit; end

  # POST /school_classes
  # POST /school_classes.json
  def create
    clone_school_class =
      SchoolClass.find_by_id(params.dig(:clone_school_class, :id))

    if clone_school_class
      @school_class =
        clone_school_class.clone_with_students_and_device_mappings(
          new_name: school_class_params[:name]
        )
    else
      @school_class = SchoolClass.new(school_class_params)
    end

    respond_to do |format|
      if @school_class.save
        CurrentSchoolClass.set @school_class

        format.html do
          redirect_url = session.delete(:redirect_to) || @school_class
          redirect_to redirect_url, notice: t('.notice')
        end
        format.json { render :show, status: :created, location: @school_class }
      else
        format.html { render :new }
        format.json do
          render json: @school_class.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /school_classes/1
  # PATCH/PUT /school_classes/1.json
  def update
    respond_to do |format|
      if @school_class.update(school_class_params)
        format.html { redirect_to @school_class, notice: t('.notice') }
        format.json { render :show, status: :ok, location: @school_class }
      else
        format.html { render :edit }
        format.json do
          render json: @school_class.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /school_classes/1
  # DELETE /school_classes/1.json
  def destroy
    @school_class.destroy
    respond_to do |format|
      format.html { redirect_to school_classes_url, notice: t('.notice') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_school_class
    @school_class = SchoolClass.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def school_class_params
    params.require(:school_class).permit(:name)
  end
end

services/web/app/views/school_classes/_form.html.haml
- create ||= create
= form_with model: @school_class, local: true do |f|
  = render "layouts/error_messages", f: f
  = f.text_field_with_label :name, autofocus: true
  - if create
    .field
      %label.label{ for: :clone_school_class_id }= t('.clone_label')
      .control
        .select
          = collection_select :clone_school_class, :id, SchoolClass.all, :id, :name, { no_field: true, prompt: t('school_classes.form.clone_prompt') }, class: 'input'
  .buttons
    = f.submit_primary t('common.save')
    = yield

services/web/app/views/school_classes/_lessons.html.haml
%h1.title
  .icon
    = icon('fas', 'paper-plane')
  = t('lessons.title')
%table.table.is-striped.is-hoverable
  %thead
    %tr
      %th= t('lessons.title')
      %th= t('common.date')
      %th= t('.average_percentage')
      %th= t('.number_of_questions')
      %th= t('.question_score_sum')
      %th= t('lessons.benchmark')
      %th
  %tbody
    - @school_class&.lessons.newest_first.each do |lesson|
      %tr
        %td= link_to lesson.name, lesson_evaluate_path(lesson)
        %td= I18n.l lesson.created_at, format: :short
        %td
          = percentage(Clickr::LessonEvaluation.new(lesson).average_percentage)
        %td= lesson.questions.count
        %td= lesson.question_score_sum
        %td= lesson.benchmark
        %td
          .buttons
            = link_to t('common.destroy'), lesson_path(lesson, redirect_back: true), method: :delete, data: { confirm: t('common.are_you_sure') }, class: 'button is-danger'

services/web/app/views/school_classes/_seating_plan.html.haml
- edit = params['edit-seating-plan'] == 'true'
- border = edit ? 1 : 0
- row_offset_to_base_1 = seating_plan.row_min - 1 - border
- col_offset_to_base_1 = seating_plan.col_min - 1 - border

-# https://johnbeatty.co/2018/03/09/stimulus-js-tutorial-how-do-i-drag-and-drop-items-in-a-list/
.seating-plan{ data: { controller: 'seating-plan',
                       'seating-plan-row-offset': row_offset_to_base_1,
                       'seating-plan-col-offset': col_offset_to_base_1,
                       'seating-plan-endpoint': seating_plan_school_class_path(school_class),
                       action: 'dragstart->seating-plan#onDragStart dragover->seating-plan#onDragOver dragenter->seating-plan#onDragEnter drop->seating-plan#onDrop dragend->seating-plan#onDragEnd',
                     },
              class: [('seating-plan--editable' if edit)].compact.join(' ') }
  - seating_plan.coordinates(border: border).each do |row, col|
    - student = seating_plan.student(row: row, col: col)
    - if student
      .seat--student{ draggable: "#{edit}",
                      data: { 'item-id': student.id,
                              row: row,
                              col: col,
                            },
                      style: "grid-row: #{row - row_offset_to_base_1}; grid-column: #{col - col_offset_to_base_1};" }
        .card
          .card-content
            %p.title.has-text-centered= student.name
          %footer.card-footer
            -# TODO Performance: Sum for all students using single group query https://api.rubyonrails.org/classes/ActiveRecord/Calculations.html
            %p.card-footer-item.has-text-weight-bold= student.question_response_sum_for_most_recent_lesson
            %p.card-footer-item.has-text-grey= student.question_response_sum
    - else
      .seat--empty{ data: { row: row, col: col },
                    onmousedown: 'setTimeout(() => this.querySelector("input[type=text]").focus(), 0)',
                    style: "grid-row: #{row - row_offset_to_base_1}; grid-column: #{col - col_offset_to_base_1};" }
        - if edit
          .card
            .card-content
              .create-student
                = form_with model: Student.new, local: true, class: 'has-text-centered' do |f|
                  = f.text_field :name
                  = f.hidden_field :school_class_id, value: school_class.id
                  = f.hidden_field :seat_row, value: row
                  = f.hidden_field :seat_col, value: col
                  = f.hidden_field :create_incomplete_mapping, value: true
                  = f.hidden_field :redirect_back, value: true
                  = f.submit_primary t('common.create')

.has-text-centered
  - if edit
    = link_to t('seating_plan.done'), { 'edit-seating-plan': nil }, class: 'button is-primary'
  - else
    = link_to t('seating_plan.edit'), { 'edit-seating-plan': true }, class: 'button is-primary'

services/web/app/views/school_classes/edit.html.haml
%h1.title= t('.title')
= render 'form' do
  = link_to t('common.back'), school_classes_path, class: 'button is-danger'
%hr/
.columns
  .column.is-12
    = render 'lessons'

services/web/app/views/school_classes/index.html.haml
%h1.title= t('.title')
= link_to t('common.new'), new_school_class_path, class: 'button is-primary'
%table.table.is-striped.is-hoverable
  %thead
    %tr
      %th= t('common.name')
      %th
  %tbody
    - @school_classes.each do |school_class|
      %tr
        %td= school_class.name
        %td
          .buttons
            = link_to t('common.show'), school_class_path(school_class), class: 'button'
            = link_to t('common.edit'), edit_school_class_path(school_class), class: 'button'
            = link_to t('common.select'), current_school_classes_path(current_school_class: { school_class_id: school_class.id }), method: :put, remote: true, class: 'button'
            = link_to t('common.destroy'), school_class, method: :delete, data: { confirm: t('common.are_you_sure') }, class: 'button is-danger'

services/web/app/views/school_classes/new.html.haml
%h1.title= t('.title')
= render 'form', create: true do
  = link_to t('common.back'), school_classes_path, class: 'button is-danger'

services/web/app/views/school_classes/show.html.haml
%p
  %b= "#{t('common.name')}:"
  = @school_class.name
.buttons
  = link_to t('common.edit'), edit_school_class_path(@school_class), class: 'button is-primary'
  = link_to I18n.t('common.back'), school_classes_path, class: 'button'
%hr/
.columns
  .column.is-12
    = render 'lessons'