services/web/config/routes.rb
Rails.application.routes.draw do
  resources :bonus_grades
  resources :buttons, only: %i[index]
  resources :student_device_mappings
  resources :question_responses
  resources :clicks
  resources :lessons do
    resource :evaluate, only: %i[show], controller: :lesson_evaluations do
      put :update_benchmark, path: :benchmark
    end
  end
  resources :questions do
    member { post :stop }
  end
  resources :students do
    member { post :adjust_score }
  end
  resources :school_classes do
    resource :seating_plan, only: %i[update show]
  end
  resource :current_school_classes, only: %i[update]
  devise_for :users

  root 'lesson_executions#show'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

services/web/app/models/lesson.rb
class Lesson < ApplicationRecord
  strip_attributes
  belongs_to :school_class
  has_many :questions, dependent: :destroy
  has_many :question_responses, dependent: :destroy

  scope :newest_first, -> { order(created_at: :desc) }
  scope :with_participation_of,
        lambda { |student:|
          threshold =
            Rails.application.config.clickr
              .student_absent_if_lesson_sum_less_than_or_equal_to
          # TODO Performance: group by having SUM() >
          where(school_class: student.school_class).select { |l|
            student.question_response_sum_for(lesson: l) > threshold
          }
        }

  validates :name, presence: true, uniqueness: { scope: :school_class }
  validates :benchmark, presence: true, numericality: { greater_than: 0 }

  def most_recent_question
    questions.last
  end

  def benchmark
    self[:benchmark] || 1.0
  end

  def has_benchmark
    self[:benchmark].present?
  end

  def question_score_sum
    questions.sum(:score)
  end
end

services/web/app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[edit update destroy]
  before_action :set_lesson_with_includes, only: %i[show]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.includes(:school_class).newest_first
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show; end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit; end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson =
      Lesson.new(
        { school_class_id: CurrentSchoolClass.get&.id, **lesson_params }
      )

    respond_to do |format|
      if @lesson.save
        SchoolClassChannel.broadcast_to(
          @lesson.school_class,
          type: SchoolClassChannel::LESSON,
          browser_window_id: params[:browser_window_id]
        )
        if params[:redirect_back]
          redirect_back fallback_location: lesson_path(@lesson),
                        notice: t('.notice') and return
        end

        format.html { redirect_to @lesson, notice: t('.notice') }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json do
          render json: @lesson.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: t('.notice') }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json do
          render json: @lesson.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html do
        if params[:redirect_back]
          redirect_back fallback_location: lessons_url, notice: t('.notice')
        else
          redirect_to lessons_url, notice: t('.notice')
        end
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def set_lesson_with_includes
    @lesson = Lesson.includes(:school_class).find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def lesson_params
    params.require(:lesson).permit(:name, :school_class_id).reject do |_, v|
      v.blank?
    end.to_h.symbolize_keys
  end
end

services/web/app/views/lessons/_form.html.haml
= form_with model: @lesson, local: true do |f|
  = render "layouts/error_messages", f: f
  = f.text_field_with_label :name, autofocus: true
  = f.collection_select_with_label :school_class_id, SchoolClass.all, :id, :name
  .buttons
    = f.submit_primary t('common.save')
    = yield

services/web/app/views/lessons/edit.html.haml
%h1.title= t('.title')
= render 'form' do
  = link_to t('common.back'), questions_path, class: 'button is-danger'

services/web/app/views/lessons/index.html.haml
%h1.title= t('.title')
= link_to t('common.new'), new_lesson_path, class: 'button is-primary'
%table.table.is-striped.is-hoverable
  %thead
    %tr
      %th= t('common.name')
      %th= t('school_classes.title')
      %th
  %tbody
    - @lessons.each do |lesson|
      %tr
        %td= lesson.name
        %td= lesson.school_class&.name
        %td
          .buttons
            = link_to t('common.show'), lesson_path(lesson), class: 'button'
            = link_to t('common.edit'), edit_lesson_path(lesson), class: 'button'
            = link_to t('common.destroy'), lesson, method: :delete, data: { confirm: t('common.are_you_sure') }, class: 'button is-danger'

services/web/app/views/lessons/new.html.haml
%h1.title= t('.title')
= render 'form' do
  = link_to t('common.back'), lessons_path, class: 'button is-danger'

services/web/app/views/lessons/show.html.haml
%p
  %b= "#{t('common.name')}:"
  = @lesson.name
%p
  %b= "#{t('school_classes.title')}:"
  = @lesson.school_class&.name
.buttons
  = link_to t('common.edit'), edit_lesson_path(@lesson), class: 'button is-primary'
  = link_to t('common.back'), lessons_path, class: 'button'