services/web/config/routes.rb
Rails.application.routes.draw do
  resources :bonus_grades
  resources :buttons, only: %i[index]
  resources :student_device_mappings
  resources :question_responses
  resources :clicks
  resources :lessons do
    resource :evaluate, only: %i[show], controller: :lesson_evaluations do
      put :update_benchmark, path: :benchmark
    end
  end
  resources :questions do
    member { post :stop }
  end
  resources :students do
    member { post :adjust_score }
  end
  resources :school_classes do
    resource :seating_plan, only: %i[update show]
  end
  resource :current_school_classes, only: %i[update]
  devise_for :users

  root 'lesson_executions#show'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

services/web/app/models/student_device_mapping.rb
class StudentDeviceMapping < ApplicationRecord
  include DeviceIdPrefixer

  strip_attributes
  belongs_to :student
  belongs_to :school_class

  scope :newest_first, -> { order(created_at: :desc) }

  validates :device_id, uniqueness: { scope: :school_class, allow_nil: true }
  validates :school_class,
            inclusion: { in: ->(mapping) { [mapping.student.school_class] } }

  before_validation :set_incomplete!

  scope :incomplete, -> { where(incomplete: true) }

  # Can't be a scope, as it returns only a single record
  def self.oldest_incomplete(device_id, school_class = CurrentSchoolClass.get)
    return nil if !school_class
    return nil if school_class.has_mapping_for(device_id)

    incomplete.where(school_class: school_class).first
  end

  def nth_incomplete(school_class = CurrentSchoolClass.get)
    return nil if !school_class
    incomplete = school_class.student_device_mappings.incomplete
    return nil if !incomplete
    incomplete.pluck(:id).index(id)
  end

  private

  def set_incomplete!
    self.incomplete = device_id.blank? || device_type.blank?
  end
end

services/web/app/controllers/student_device_mappings_controller.rb
class StudentDeviceMappingsController < ApplicationController
  before_action :set_student_device_mapping, only: %i[edit update destroy]
  before_action :set_student_device_mapping_with_includes, only: %i[show]

  # GET /student_device_mappings
  # GET /student_device_mappings.json
  def index
    @student_device_mappings =
      StudentDeviceMapping.includes(:student, :school_class).newest_first
  end

  # GET /student_device_mappings/1
  # GET /student_device_mappings/1.json
  def show; end

  # GET /student_device_mappings/new
  def new
    @student_device_mapping = StudentDeviceMapping.new
  end

  # GET /student_device_mappings/1/edit
  def edit; end

  # POST /student_device_mappings
  # POST /student_device_mappings.json
  def create
    @student_device_mapping =
      StudentDeviceMapping.new(student_device_mapping_params)
    # TODO set missing data

    respond_to do |format|
      if @student_device_mapping.save
        format.html do
          redirect_to @student_device_mapping, notice: t('.notice')
        end
        format.json do
          render :show, status: :created, location: @student_device_mapping
        end
      else
        format.html { render :new }
        format.json do
          render json: @student_device_mapping.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /student_device_mappings/1
  # PATCH/PUT /student_device_mappings/1.json
  def update
    respond_to do |format|
      if @student_device_mapping.update(student_device_mapping_params)
        format.html do
          redirect_to @student_device_mapping, notice: t('.notice')
        end
        format.json do
          render :show, status: :ok, location: @student_device_mapping
        end
      else
        format.html { render :edit }
        format.json do
          render json: @student_device_mapping.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /student_device_mappings/1
  # DELETE /student_device_mappings/1.json
  def destroy
    @student_device_mapping.destroy
    respond_to do |format|
      format.html do
        redirect_to student_device_mappings_url, notice: t('.notice')
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_student_device_mapping
    @student_device_mapping = StudentDeviceMapping.find(params[:id])
  end

  def set_student_device_mapping_with_includes
    @student_device_mapping =
      StudentDeviceMapping.includes(:student, :school_class).find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def student_device_mapping_params
    params.require(:student_device_mapping).permit(
      :student_id,
      :school_class_id,
      :device_id,
      :device_type
    )
  end
end

services/web/app/views/student_device_mappings/_form.html.haml
= form_with model: @student_device_mapping, local: true do |f|
  = render "layouts/error_messages", f: f
  = f.collection_select_with_label :student_id, Student.all, :id, :name, {}, autofocus: true
  = f.collection_select_with_label :school_class_id, SchoolClass.all, :id, :name, {}, autofocus: true
  = f.text_field_with_label :device_id
  = f.text_field_with_label :device_type
  .buttons
    = f.submit_primary t('common.save')
    = yield

services/web/app/views/student_device_mappings/edit.html.haml
%h1.title= t('.title')
= render 'form' do
  = link_to t('common.back'), student_device_mappings_path, class: 'button is-danger'

services/web/app/views/student_device_mappings/index.html.haml
%h1.title= t('.title')
= link_to t('common.new'), new_student_device_mapping_path, class: 'button is-primary'
%table.table.is-striped.is-hoverable
  %thead
    %tr
      %th= t('students.title')
      %th= t('school_classes.title')
      %th= t('devices.device')
      %th= t('devices.device_type')
      %th
  %tbody
    - @student_device_mappings.each do |student_device_mapping|
      %tr
        %td= student_device_mapping.student&.name
        %td= student_device_mapping.school_class&.name
        %td= student_device_mapping.device_id
        %td= student_device_mapping.device_type
        %td
          .buttons
            = link_to t('common.show'), student_device_mapping_path(student_device_mapping), class: 'button'
            = link_to t('common.edit'), edit_student_device_mapping_path(student_device_mapping), class: 'button'
            = link_to t('common.destroy'), student_device_mapping, method: :delete, data: { confirm: t('common.are_you_sure') }, class: 'button is-danger'

services/web/app/views/student_device_mappings/new.html.haml
%h1.title= t('.title')
= render 'form' do
  = link_to t('common.back'), student_device_mappings_path, class: 'button is-danger'

services/web/app/views/student_device_mappings/show.html.haml
%p
  %b= "#{t('students.title')}:"
  = @student_device_mapping.student&.name
%p
  %b= "#{t('school_classes.title')}:"
  = @student_device_mapping.school_class&.name
%p
  %b= "#{t('devices.device')}:"
  = @student_device_mapping.device_id
%p
  %b= "#{t('devices.device_type')}:"
  = @student_device_mapping.device_type
.buttons
  = link_to t('common.edit'), edit_student_device_mapping_path(@student_device_mapping), class: 'button is-primary'
  = link_to t('common.back'), student_device_mappings_path, class: 'button'